version: '3'
services:
  server:
    build: ./server
    ports:
      - 8080:8080
    volumes:
      - ./server:/app
    restart: on-failure
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: on-failure
    environment:
      - CHOKIDAR_USEPOLLING=true
